resources:
- deployment.yaml
- ingress.yaml
- namespace.yaml
- service.yaml
- tls.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: georgecao
  kubernetes.ops.region: hk
namespace: gitea-repo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/gitea-build
  newTag: 6b8591254cd6577c4114dc4140b79453515a6848811a1bfcc52519c6131a4f7a
